/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankIndexRouteImport } from './routes/rank/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as DuelIndexRouteImport } from './routes/duel/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as DashboardUsernameRouteImport } from './routes/dashboard/$username'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankIndexRoute = RankIndexRouteImport.update({
  id: '/rank/',
  path: '/rank/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelIndexRoute = DuelIndexRouteImport.update({
  id: '/duel/',
  path: '/duel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsernameRoute = DashboardUsernameRouteImport.update({
  id: '/dashboard/$username',
  path: '/dashboard/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$username': typeof DashboardUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/duel/': typeof DuelIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/rank/': typeof RankIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$username': typeof DashboardUsernameRoute
  '/about': typeof AboutIndexRoute
  '/duel': typeof DuelIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/rank': typeof RankIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$username': typeof DashboardUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/duel/': typeof DuelIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/rank/': typeof RankIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/$username'
    | '/about/'
    | '/duel/'
    | '/leaderboard/'
    | '/rank/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$username'
    | '/about'
    | '/duel'
    | '/leaderboard'
    | '/rank'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard/$username'
    | '/about/'
    | '/duel/'
    | '/leaderboard/'
    | '/rank/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardUsernameRoute: typeof DashboardUsernameRoute
  AboutIndexRoute: typeof AboutIndexRoute
  DuelIndexRoute: typeof DuelIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  RankIndexRoute: typeof RankIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank/': {
      id: '/rank/'
      path: '/rank'
      fullPath: '/rank/'
      preLoaderRoute: typeof RankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/': {
      id: '/duel/'
      path: '/duel'
      fullPath: '/duel/'
      preLoaderRoute: typeof DuelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$username': {
      id: '/dashboard/$username'
      path: '/dashboard/$username'
      fullPath: '/dashboard/$username'
      preLoaderRoute: typeof DashboardUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardUsernameRoute: DashboardUsernameRoute,
  AboutIndexRoute: AboutIndexRoute,
  DuelIndexRoute: DuelIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  RankIndexRoute: RankIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
